version: '2.2'

services:
  news:
    restart: always
    build:
      context: .
    env_file: .env
    cpus: 2
    mem_limit: 256m
    ports:
      - '5001:5001'
    volumes:
      -  /news
    depends_on: 
      news_db:
        condition: service_healthy

  parser:
    restart: 'no'
    build:
      context: .
    env_file: .env
    volumes:
      -  /news
    depends_on: 
      news_db:
        condition: service_healthy

  tasks:
    restart: 'no'
    build:
      context: .
    env_file: .env
    volumes:
      -  /news
    depends_on: 
      news_db:
        condition: service_healthy
    command: celery -A parser_run_task worker -B --loglevel=INFO

  news_db:
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - newsdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  
  redis:
    image: redis:6.2
    volumes:
      - redisdata:/storage/redis/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - 6379:6380
    command: redis-server --appendonly yes

volumes:
  newsdata:
  redisdata: